/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mylapy.glb 
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, useFBX, useAnimations } from '@react-three/drei'
import { useGraph, useFrame } from '@react-three/fiber'
import { SkeletonUtils } from 'three-stdlib'

export function Mylapy(props) {
  const { onScreenClick } = props;
  const model = useRef();
  const screenRef = useRef();
  
  const { scene } = useGLTF('/models/mylapy.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  
  // Load the open animation
  const { animations: openAnimation } = useFBX('/animations/open.fbx');
  
  // Set animation name
  if (openAnimation[0]) {
    openAnimation[0].name = "Open";
  }
  
  // Setup animations
  const { actions } = useAnimations(openAnimation, model);
  
  // Play the open animation when component mounts
  useEffect(() => {
    if (actions.Open) {
      actions.Open.reset().play();
    }
    return () => {
      if (actions.Open) {
        actions.Open.stop();
      }
    }
  }, [actions]);

  // Handle screen click
  const handleScreenClick = (event) => {
    event.stopPropagation();
    if (onScreenClick) {
      onScreenClick();
    }
  };

  return (
    <group {...props} ref={model} dispose={null}>
      <group position={[0, 0.133, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -0.112, -0.111]} rotation={[-0.136, 0, 0]} scale={0.039}>
            <mesh geometry={nodes.Object_20.geometry} material={materials.monitor} />
            <mesh geometry={nodes.Object_21.geometry} material={materials.metal_logo} />
            {/* Clickable screen */}
            <mesh 
              ref={screenRef}
              geometry={nodes.Object_22.geometry} 
              material={materials.displauy}
              onClick={handleScreenClick}
              onPointerOver={() => document.body.style.cursor = 'pointer'}
              onPointerOut={() => document.body.style.cursor = 'default'}
            />
            <mesh geometry={nodes.Object_23.geometry} material={materials.material_12} />
            <mesh geometry={nodes.Object_24.geometry} material={materials.material_12} />
            <mesh geometry={nodes.Object_25.geometry} material={materials.line} />
            <mesh geometry={nodes.Object_26.geometry} material={materials.cam_mat} />
            <mesh geometry={nodes.Object_27.geometry} material={materials.kosong} />
            <mesh geometry={nodes.Object_28.geometry} material={materials.camg} />
            <mesh geometry={nodes.Object_29.geometry} material={materials.kaca_mga} />
          </group>
          <group position={[0, -0.112, -0.046]} scale={0.115}>
            <mesh geometry={nodes.Object_35.geometry} material={materials.material_18} />
            <mesh geometry={nodes.Object_36.geometry} material={materials['Material.001']} />
          </group>
          <group position={[0, -0.112, -0.046]} scale={0.115}>
            <mesh geometry={nodes.Object_8.geometry} material={materials.numpad} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.text} />
          </group>
          <group position={[0, -0.112, -0.046]} scale={0.115}>
            <mesh geometry={nodes.Object_44.geometry} material={materials.body_metal} />
            <mesh geometry={nodes.Object_45.geometry} material={materials.kosong} />
          </group>
          <group position={[0, -0.112, -0.046]} scale={0.115}>
            <mesh geometry={nodes.Object_47.geometry} material={materials.body_metal} />
            <mesh geometry={nodes.Object_48.geometry} material={materials.kaki} />
          </group>
          <group position={[0, -0.112, -0.046]} scale={0.115}>
            <mesh geometry={nodes.Object_54.geometry} material={materials.body_metal} />
            <mesh geometry={nodes.Object_55.geometry} material={materials.kosong} />
          </group>
          <group position={[0, -0.099, -0.064]} rotation={[0.175, 0, 0]} scale={0.115}>
            <mesh geometry={nodes.Object_13.geometry} material={materials.body_metal} />
            <mesh geometry={nodes.Object_14.geometry} material={materials.body_panel} />
            <mesh geometry={nodes.Object_15.geometry} material={materials.panel_2} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.logo_rough} />
          </group>
          <group position={[0, -0.112, -0.046]} scale={0.115}>
            <mesh geometry={nodes.Object_67.geometry} material={materials.colokan} />
            <mesh geometry={nodes.Object_68.geometry} material={materials.kosong} />
          </group>
          <group position={[0, -0.112, -0.046]} scale={0.115}>
            <mesh geometry={nodes.Object_72.geometry} material={materials.heatsink} />
            <mesh geometry={nodes.Object_73.geometry} material={materials.kosong} />
          </group>
          <group position={[0, -0.112, -0.046]} scale={0.115}>
            <mesh geometry={nodes.Object_38.geometry} material={materials.body_metal} />
            <mesh geometry={nodes.Object_39.geometry} material={materials.body_panel} />
            <mesh geometry={nodes.Object_40.geometry} material={materials.rgb_inside} />
            <mesh geometry={nodes.Object_41.geometry} material={materials.kosong} />
            <mesh geometry={nodes.Object_42.geometry} material={materials.metal_bar} />
          </group>
          <mesh geometry={nodes.Object_31.geometry} material={materials.logo_rough} position={[0, -0.112, -0.046]} scale={0.115} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.heatsink} position={[0, -0.112, -0.046]} scale={0.115} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.material} position={[0, -0.099, -0.127]} rotation={[-0.051, 0, 0]} scale={0.115} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.body_metal} position={[0, -0.112, -0.046]} scale={0.115} />
          <mesh geometry={nodes.Object_52.geometry} material={materials.logo_rough} position={[0, -0.112, -0.046]} scale={0.115} />
          <mesh geometry={nodes.Object_57.geometry} material={materials.kosong} position={[0, -0.112, -0.046]} scale={0.115} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.keycap} position={[0, -0.112, -0.046]} scale={0.115} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.body_metal} position={[0, -0.104, -0.045]} rotation={[-0.116, 0, 0]} scale={0.115} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.kosong} position={[0, -0.112, -0.046]} scale={0.115} />
          <mesh geometry={nodes.Object_59.geometry} material={materials.body_metal} position={[0, -0.112, -0.046]} scale={0.115} />
          <mesh geometry={nodes.Object_61.geometry} material={materials.body_metal} position={[0, -0.112, -0.046]} scale={0.115} />
          <mesh geometry={nodes.Object_63.geometry} material={materials.kaca_mga} position={[0, -0.112, -0.046]} scale={0.115} />
          <mesh geometry={nodes.Object_65.geometry} material={materials.rgb_semi} position={[0, -0.112, -0.046]} scale={0.115} />
          <mesh geometry={nodes.Object_70.geometry} material={materials.body_metal} position={[0, -0.112, -0.046]} scale={0.115} />
          <mesh geometry={nodes.Object_77.geometry} material={materials.text} position={[0, -0.112, -0.046]} scale={0.115} />
          <mesh geometry={nodes.Object_79.geometry} material={materials.text} position={[0, -0.112, -0.046]} scale={0.115} />
          <mesh geometry={nodes.Object_81.geometry} material={materials.text} position={[0, -0.112, -0.046]} scale={0.115} />
          <mesh geometry={nodes.Object_75.geometry} material={materials.logo_rough} position={[0, -0.112, -0.046]} scale={0.115} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/mylapy.glb')
useFBX.preload('/animations/open.fbx')
